/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.securityform;


import com.raven.dbfunction.User;
import com.raven.classes.CustomerClass;
import com.raven.classes.UsersClass;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Panel;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author RAVEN
 */
public class Camera_Security extends javax.swing.JPanel {
    private void showCameraImage(BufferedImage image) {
    int panelW = rightPanel.getWidth();
    int panelH = rightPanel.getHeight();

    Image scaled = getScaledImage(image, panelW, panelH);
    JLabel lblImage = new JLabel(new ImageIcon(scaled));
    lblImage.setHorizontalAlignment(JLabel.CENTER);
    lblImage.setVerticalAlignment(JLabel.CENTER);

    rightPanel.removeAll();
    rightPanel.setLayout(new BorderLayout());
    rightPanel.add(lblImage, BorderLayout.CENTER);
    rightPanel.revalidate();
    rightPanel.repaint();
}

private Image getScaledImage(Image srcImg, int maxW, int maxH) {
    int srcW = srcImg.getWidth(null);
    int srcH = srcImg.getHeight(null);
    float scale = Math.min((float) maxW / srcW, (float) maxH / srcH);
    int newW = Math.round(srcW * scale);
    int newH = Math.round(srcH * scale);
    return srcImg.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
}

    

    

    public Camera_Security() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        btnCamera1 = new javax.swing.JButton();
        btnCamera2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        btnCamera1.setText("Camera 1");
        btnCamera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamera1ActionPerformed(evt);
            }
        });

        btnCamera2.setText("Camera 2");
        btnCamera2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamera2ActionPerformed(evt);
            }
        });

        jButton3.setText("Camera 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCamera1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addComponent(btnCamera2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnCamera1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnCamera2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCamera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamera1ActionPerformed
        try {
            BufferedImage img = ImageIO.read(new File("F:\\Code\\Java\\DOAN - Ver 0.6\\CGMApp - 2352025 - 1.9\\CGMApp - 2352025 - 1.2.1\\src\\com\\raven\\images\\CCTV1.jpg"));
            showCameraImage(img);
        } catch (IOException ex) {
            Logger.getLogger(Camera_Security.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCamera1ActionPerformed

    private void btnCamera2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamera2ActionPerformed
        try {
            BufferedImage img = ImageIO.read(new File("F:\\Code\\Java\\DOAN - Ver 0.6\\CGMApp - 2352025 - 1.9\\CGMApp - 2352025 - 1.2.1\\src\\com\\raven\\images\\CCTV2.jpg"));
            showCameraImage(img);
        } catch (IOException ex) {
            Logger.getLogger(Camera_Security.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCamera2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            BufferedImage img = ImageIO.read(new File("F:\\Code\\Java\\DOAN - Ver 0.6\\CGMApp - 2352025 - 1.9\\CGMApp - 2352025 - 1.2.1\\src\\com\\raven\\images\\CCTV3.jpg"));
            showCameraImage(img);
        } catch (IOException ex) {
            Logger.getLogger(Camera_Security.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamera1;
    private javax.swing.JButton btnCamera2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
